profiles:
  fasrc:
    # dashboard_title property does not work yet
    # It requires a new change to the OnDemand Puppet Module. PR raised.
    dashboard_title: FASRC
    dashboard_header_img_logo: "/public/fasrc_logo.png"
    brand_bg_color: "rgb(157,47,60)"
    brand_link_active_bg_color: "rgb(59, 61, 63)"

    disable_dashboard_welcome_message: true

    pinned_apps_group_by: "category"
    pinned_apps:
      - sys/RStudio
      - sys/rdesktop

    dashboard_layout:
      rows:
        - columns:
            - width: 10
              widgets:
                - "pinned_apps"
                - "motd"