support_ticket_basic:
  email:
    to: "support@support.system.com"

support_ticket:
  description: |
    This is a description text for the frontend

  #ui_template: "rt_service_template"
  attributes:
    email:
      required: true
    subject:
      value: "OnDemand Problem: "
  rt_api:
    server: "http://rt:34000"
    user: "root"
    pass: "password"
    priority: 4
    queues:
      - "General"
  email_bak:
    email_template_: "custom_template"
    from_: "config@example.com"
    to: "support@support.system.com"
    delivery_method_back: "smtp"
    delivery_settings:
      address: "host.docker.internal"
      port: "25"
      open_timeout: 30
      read_timeout: 30